theme: jekyll-theme-minimal
title: Autocomplete.sh LLMs in your terminal
description: Stop getting stuck in the terminal, just press tab twice to ask OpenAI for help.  Command suggestions based on your history, terminal environment and query.

